# Generated by Django 5.1.1 on 2024-09-11 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('UsuarioID', models.AutoField(db_column='UsuarioID', primary_key=True, serialize=False)),
                ('Username', models.CharField(db_column='Username', max_length=100)),
                ('Password', models.CharField(db_column='Password', max_length=100)),
                ('Email', models.EmailField(db_column='Email', max_length=100)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('Tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Instructor', 'Instructor')], db_column='Tipo', max_length=10)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('EspecialidadID', models.AutoField(db_column='EspecialidadID', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='Estado', default='Activo', max_length=10)),
                ('FechaCreacion', models.DateField(db_column='FechaCreacion', default=django.utils.timezone.now)),
                ('FechaActualizacion', models.DateField(auto_now=True, db_column='FechaActualizacion')),
            ],
            options={
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('LocalID', models.AutoField(db_column='LocalID', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Direccion', models.CharField(db_column='Direccion', max_length=255)),
                ('Telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Local',
            },
        ),
        migrations.CreateModel(
            name='TipoDeRutina',
            fields=[
                ('TipoDeRutinaID', models.AutoField(db_column='TipoDeRutinaID', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('Descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'TipoDeRutina',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ClienteID', models.OneToOneField(db_column='ClienteID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rutina.usuario')),
                ('Talla', models.DecimalField(blank=True, db_column='Talla', decimal_places=2, max_digits=5, null=True)),
                ('PorcentajeGrasaCorporal', models.DecimalField(blank=True, db_column='PorcentajeGrasaCorporal', decimal_places=2, max_digits=5, null=True)),
                ('NivelCondicionFisica', models.CharField(blank=True, db_column='NivelCondicionFisica', max_length=50, null=True)),
                ('ObjetivoPrincipal', models.CharField(blank=True, db_column='ObjetivoPrincipal', max_length=255, null=True)),
                ('HistorialLesiones', models.TextField(blank=True, db_column='HistorialLesiones', null=True)),
                ('EnfermedadesPreexistentes', models.TextField(blank=True, db_column='EnfermedadesPreexistentes', null=True)),
                ('PreferenciasEntrenamiento', models.TextField(blank=True, db_column='PreferenciasEntrenamiento', null=True)),
                ('FechaRegistro', models.DateField(db_column='FechaRegistro', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='EspecialidadInstructor',
            fields=[
                ('EspecialidadInstructorID', models.AutoField(db_column='EspecialidadInstructorID', primary_key=True, serialize=False)),
                ('EspecialidadID', models.ForeignKey(db_column='EspecialidadID', on_delete=django.db.models.deletion.CASCADE, to='rutina.especialidad')),
            ],
            options={
                'db_table': 'EspecialidadInstructor',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('InstructorID', models.AutoField(db_column='InstructorID', primary_key=True, serialize=False)),
                ('Nombres', models.CharField(db_column='Nombres', max_length=100)),
                ('Apellidos', models.CharField(db_column='Apellidos', max_length=100)),
                ('Email', models.EmailField(db_column='Email', max_length=100)),
                ('Edad', models.IntegerField(db_column='Edad')),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], db_column='Sexo', max_length=1)),
                ('FechaNacimiento', models.DateField(db_column='FechaNacimiento')),
                ('Especialidad', models.ManyToManyField(db_column='EspecialidadID', related_name='instructores', through='rutina.EspecialidadInstructor', to='rutina.especialidad')),
                ('Local', models.ForeignKey(blank=True, db_column='LocalID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rutina.local')),
            ],
            options={
                'db_table': 'Instructor',
            },
        ),
        migrations.CreateModel(
            name='InformacionPersonalInstructor',
            fields=[
                ('InfoPersonalID', models.AutoField(db_column='InfoPersonalID', primary_key=True, serialize=False)),
                ('PreferenciaHorario', models.CharField(db_column='PreferenciaHorario', max_length=100)),
                ('InstructorID', models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='rutina.instructor')),
            ],
            options={
                'db_table': 'InformacionPersonalInstructor',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('HorarioID', models.AutoField(db_column='HorarioID', primary_key=True, serialize=False)),
                ('Dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], db_column='Dia', max_length=10)),
                ('HoraInicio', models.TimeField(db_column='HoraInicio')),
                ('HoraFin', models.TimeField(db_column='HoraFin')),
                ('InstructorID', models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='rutina.instructor')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
        migrations.AddField(
            model_name='especialidadinstructor',
            name='InstructorID',
            field=models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='rutina.instructor'),
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('RutinaID', models.AutoField(db_column='RutinaID', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('Descripcion', models.TextField(db_column='Descripcion', null=True)),
                ('Frecuencia', models.TextField(db_column='Frecuencia', max_length=50)),
                ('FechaInicio', models.DateField(db_column='FechaInicio')),
                ('FechaFin', models.DateField(db_column='FechaFin')),
                ('Imagen1', models.ImageField(blank=True, db_column='Imagen1', null=True, upload_to='imagenes/')),
                ('Imagen2', models.ImageField(blank=True, db_column='Imagen2', null=True, upload_to='imagenes/')),
                ('Objetivos', models.CharField(db_column='Objetivos', max_length=255)),
                ('InstructorID', models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='rutina.instructor')),
                ('TipoID', models.ForeignKey(db_column='TipoID', on_delete=django.db.models.deletion.CASCADE, to='rutina.tipoderutina')),
                ('ClienteID', models.ForeignKey(blank=True, db_column='ClienteID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutina.cliente')),
            ],
            options={
                'db_table': 'Rutina',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('MetaID', models.AutoField(db_column='MetaID', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('EstadoInicial', models.DecimalField(db_column='EstadoInicial', decimal_places=2, max_digits=5)),
                ('EstadoFinal', models.DecimalField(db_column='EstadoFinal', decimal_places=2, max_digits=5)),
                ('RutinaID', models.ForeignKey(db_column='RutinaID', on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='rutina.rutina')),
            ],
            options={
                'db_table': 'Meta',
            },
        ),
        migrations.CreateModel(
            name='MetaPredeterminada',
            fields=[
                ('MetaPredeterminadaID', models.AutoField(db_column='MetaPredeterminadaID', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('TipoDeRutinaID', models.ForeignKey(db_column='TipoDeRutinaID', on_delete=django.db.models.deletion.CASCADE, to='rutina.tipoderutina')),
            ],
            options={
                'db_table': 'MetaPredeterminada',
            },
        ),
        migrations.AlterUniqueTogether(
            name='especialidadinstructor',
            unique_together={('InstructorID', 'EspecialidadID')},
        ),
        migrations.CreateModel(
            name='TipoDeRutinaEspecialidad',
            fields=[
                ('TipoDeRutinaEspecialidadID', models.AutoField(db_column='TipoDeRutinaEspecialidadID', primary_key=True, serialize=False)),
                ('EspecialidadID', models.ForeignKey(db_column='EspecialidadID', on_delete=django.db.models.deletion.CASCADE, to='rutina.especialidad')),
                ('TipoDeRutinaID', models.ForeignKey(db_column='TipoDeRutinaID', on_delete=django.db.models.deletion.CASCADE, to='rutina.tipoderutina')),
            ],
            options={
                'db_table': 'TipoDeRutinaEspecialidad',
                'unique_together': {('TipoDeRutinaID', 'EspecialidadID')},
            },
        ),
    ]
