# Generated by Django 5.1 on 2024-09-03 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('HorarioID', models.AutoField(db_column='HorarioID', primary_key=True, serialize=False)),
                ('Dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], db_column='Dia', max_length=10)),
                ('HoraInicio', models.TimeField(db_column='HoraInicio')),
                ('HoraFin', models.TimeField(db_column='HoraFin')),
                ('InstructorID', models.ForeignKey(db_column='InstructorID', on_delete=django.db.models.deletion.CASCADE, to='rutina.instructor')),
            ],
            options={
                'db_table': 'Horario',
            },
        ),
    ]
