# Generated by Django 5.1 on 2024-08-28 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_local_instructor_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_condicion_fisica', models.CharField(blank=True, max_length=50, null=True)),
                ('objetivo_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('historial_lesiones', models.TextField(blank=True, null=True)),
                ('enfermedades_preexistentes', models.TextField(blank=True, null=True)),
                ('preferencias_entrenamiento', models.TextField(blank=True, null=True)),
                ('disponibilidad_horaria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rutina.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutina.cliente'),
        ),
        migrations.DeleteModel(
            name='InscripcionRutina',
        ),
    ]
