# Generated by Django 5.1 on 2024-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutina',
            name='HorasRecomendadas',
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='EstadoFinal',
            field=models.CharField(db_column='EstadoFinal', max_length=50),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='EstadoInicial',
            field=models.CharField(db_column='EstadoInicial', max_length=50),
        ),
    ]
