# Generated by Django 5.1 on 2024-09-02 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0003_cliente_rutina_cliente_delete_inscripcionrutina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rutina',
            old_name='dias_recomendados',
            new_name='horas_recomendadas',
        ),
        migrations.AddField(
            model_name='frecuencia',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rutina.instructor'),
        ),
    ]
